#%RAML 1.0 Library

types:
  ProductItem:
    type: object
    properties:
      product_id: string
      quantity: integer
  Order:
    type: object
    properties:
      order_id: string
      creation_date: string
      items: ProductItem[]
  Orders:
    type: object
    properties:
      orders: Order[]
